TEMP: Disable healthd extension
* frameworks/native/include/binder/Parcel.h:23:10: fatal error: 'android-base/unique_fd.h' file not found
  -> Recent changes in master introduced that, O probably is fine